apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: python-random-netpol
spec:
  podSelector:
    matchLabels:
      app: python-random
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: getting-random
    ports:
    - protocol: TCP
      port: 5000
