apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: golang-random-netpol
spec:
  podSelector:
    matchLabels:
      app: golang-random
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: getting-random
    ports:
    - protocol: TCP
      port: 8081
