apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: js-random-netpol
spec:
  podSelector:
    matchLabels:
      app: js-random
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: getting-random
    ports:
    - protocol: TCP
      port: 8083
