apiVersion: v1
kind: Service
metadata:
  name: getting-random-service
spec:
  selector:
    app: getting-random
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
